### ISSUE TITLE
Any way to get the information from a side-directory / submodule?

### ISSUE THREAD

**Issue by masklinn** [jwodder/versioningit#100]
I'm trying to build a precompiled wheel for data files from an other repository, I would like to follow the versioning scheme of the data repository *but* the precompiled wheel lives in a multi-projects repository, so it can't be tagged itself.

`versioningit` seems like it almost works, but I can't find a way to tell it to run git against an other directory than `PROJECT_ROOT`. Is there a way to do that?

**Comment by jwodder** [comment]
Using a custom project root would require invoking `versioningit` via [the library API](https://versioningit.readthedocs.io/en/stable/api.html) in a `setup.py` file (assuming you're using setuptools; I can't really help you with other build backends).

Assuming all your other project metadata is in `setup.cfg` or `pyproject.toml`, you would need a `setup.py` that looks like:

```python
from setuptools import setup
from versioningit import get_version

setup(
    version=get_version(
        "path/to/side-directory",
        # I'm assuming that the side directory does not contain a `pyproject.toml` file
        # with a `[tool.versioningit]` table, so you'll need to provide the versioningit
        # config here.  An empty config should take care of the simple cases, but see the
        # docs if you need something nontrivial. 
        config={},
    ),
)
```

**Comment by masklinn** [comment]
I’m using hatch in this case, but I assume it’s conceptually similar, I just need to find how dynamic versions work there. 

thanks.
