### ISSUE TITLE
no debug messages after setting log level to DEBUG.

### ISSUE THREAD

**Issue by metaperl** [jwodder/versioningit#19]
As shown in [this video](https://youtu.be/sws6n8gFrR4) there are no debug messages emitted from versioningit even after setting the environmental variable.

**Comment by jwodder** [comment]
Ah, so you were running the `versioningit` command with `VERSIONINGIT_LOG_LEVEL=DEBUG` and wondering why there were no debug messages.  The answer is that `VERSIONINGIT_LOG_LEVEL` (currently) only takes effect when invoking the setuptools hook — i.e., when building your project or when running `setup.py --version`.  If you want debug information for the command, you have to pass the `-v`/`--verbose` option (Pass it twice for maximum debugging).

That said, the command really should honor `VERSIONINGIT_LOG_LEVEL`; excuse me while I go implement that.
