### ISSUE TITLE
file not written to after configuring the write subtable

### ISSUE THREAD

**Issue by metaperl** [jwodder/versioningit#20]
In [this repo](https://github.com/metaperl/mlm-sim) I have a [pyproject.toml](https://github.com/metaperl/mlm-sim/blob/main/pyproject.toml) that I was expecting to write to a file named `_version.py` but it did not.

**Comment by metaperl** [comment]
I figured it out by reading further in the docs... you have to supply a `--write` flag to the command-line script. But it would be nice if [this section](https://github.com/jwodder/versioningit#the-tool-versioningit-write-subtable) at least mentioned that to avoid others having the same confusion.

**Comment by jwodder** [comment]
I've added a note to the docs in commit 8332f79.  You can see the results in the new Read the Docs site at https://versioningit.readthedocs.io/en/latest/configuration.html#the-tool-versioningit-write-subtable.
