### ISSUE TITLE
In what way does versioningit replace the need for (and will overwrite) the version keyword to the setup() function?

### ISSUE THREAD

**Issue by metaperl** [jwodder/versioningit#21]
In [the docs](https://github.com/jwodder/versioningit#installation--setup) we read:

> versioningit replaces the need for (and will overwrite) the version keyword to the setup() function, so you should remove any such keyword from your setup.py/setup.cfg to reduce confusion.

But it has not been my experience that the versioningit command-line program overwrites the version keyword in setup.py.

I have the following setup.py

```

from setuptools import setup

from versioningit import get_version

setup(
    name='mlm_sim',
    version=get_version(write=True),
    packages=['mlm_sim'],
    install_requires=[
        'requests',
    ],
)

```

and `python setup.py --version` returns a version but without overwriting anything....

**Comment by jwodder** [comment]
What you're doing is not the normal way to use versioningit.  The normal way is to declare & configure it purely through `pyproject.toml`; when you do this and then build your project (using [build](https://github.com/pypa/build) or another PEP 517 frontend), a hook in versioningit will be invoked that will cause the version in the project metadata to be set to the Git-derived version that versioningit calculates.  When this happens, any version set in the `version` argument to `setup()` will be discarded; this is what the quoted text is referring to.
