### ISSUE TITLE
versioningit and project metadata in pyproject.toml (PEP 621)

### ISSUE THREAD

**Issue by bastimeyer** [jwodder/versioningit#26]
Hi, first off, thanks for creating this project! :+1:

I've been trying on switching our project to [PEP 518](https://peps.python.org/pep-0518/) build system declarations via `pyproject.toml`, and `versioneer` was a road blocker for us the entire time because of its lack of support, and `setuptools_scm` didn't fit because of its strict version string format which we don't want. `versioningit` on the other hand does everything right and is customizable, and so far, (almost) everything's working well.

One thing that required a bit of extra research was getting the right version in editable installs via `tool.versioningit.build` and setting up the version template replacement (#8), but everything else was dead simple.

However, the one final issue I'm facing is my attempt to move project metadata from `setup.cfg` to `pyproject.toml` ([PEP 621](https://peps.python.org/pep-0621/)). Adding metadata to the `[project]` table in pyproject.toml also requires setting the `project.version` property with its value being a string compatible with [PEP 440](https://peps.python.org/pep-0440/), otherwise it won't build and it returns the following errors:

> configuration error: `project` must contain ['version'] properties
> configuration error: `project.version` must be pep440

That's why I set it to `0.0.0+unknown` in my expectation that this static version string would get replaced by versioningit when building. Unfortunately though, having the `project.version` property set results in having a static version string when building instead of the one calculated by versioningit. Editable installs via `pip install -e .` don't have this problem because the template file does not get replaced with the static string and the version gets calculated during runtime, but pip will still log the static version string when creating the editable install. When the metadata is left in setup.cfg (no mandatory version field here), this obviously won't cause any issues and everything works as expected.

I could of course leave the project metadata in setup.cfg and stop here, but according to setuptools, they are planning on deprecating the setup.cfg file format in favor of having a single pyproject.toml configuration:
https://github.com/pypa/setuptools/milestone/7

So my question is, is this a bug in versioningit, or is this an issue with how setuptools reads the metadata which needs to get fixed upstream?

Thanks for your help!

**Comment by jwodder** [comment]
Since the project version isn't being set statically, you don't want to specify it via `project.version`, and so you need to set `project.dynamic = ["version"]` in addition to the `versioningit` configuration.  If that doesn't work, could you point me to a repository where you're trying to set this all up?

**Comment by bastimeyer** [comment]
> project.dynamic = ["version"]

I have no idea how I missed that. Thank you very much.
