### ISSUE TITLE
how to "package" source distributions from PyPI distribution (e.g. for Debian)...?

### ISSUE THREAD

**Issue by yarikoptic** [jwodder/versioningit#28]
Now that heudiconv released with use of versioningit, I have tried to update its debian package (packaging at https://salsa.debian.org/med-team/heudiconv/) where it would get new sources from pypi's tar.gz .

versioningit relies exclusively on the distributed .tar.gz shipping heudiconv.egg-info with PKG-INFO which has the version specified.
The "tricky" issue I encountered is that from that .tar.gz, if "derived" distribution (e.g. via `python setup.py sdist`) is attempted, it overwrites `heudiconv.egg-info/PKG-INFO` with new information containing dummy 0.0.0 version!

<details>
<summary>detailed log</summary> 

```shell
lena:/tmp/heudiconv-0.11.1
$> cat heudiconv.egg-info/PKG-INFO 
Metadata-Version: 2.1
Name: heudiconv
Version: 0.11.1
Summary: Heuristic DICOM Converter
Author: HeuDiConv team and contributors
License: Apache 2.0
Classifier: Environment :: Console
Classifier: Intended Audience :: Science/Research
Classifier: License :: OSI Approved :: Apache Software License
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Classifier: Topic :: Scientific/Engineering
Requires-Python: >=3.7
Provides-Extra: tests
Provides-Extra: extras
Provides-Extra: datalad
Provides-Extra: all
License-File: LICENSE

Convert DICOM dirs based on heuristic info - HeuDiConv
uses the dcmstack package and dcm2niix tool to convert DICOM directories or
tarballs into collections of NIfTI files following pre-defined heuristic(s).

$> python3 setup.py sdist
running sdist
running egg_info
writing heudiconv.egg-info/PKG-INFO
writing dependency_links to heudiconv.egg-info/dependency_links.txt
writing entry points to heudiconv.egg-info/entry_points.txt
writing requirements to heudiconv.egg-info/requires.txt
writing top-level names to heudiconv.egg-info/top_level.txt
listing git files failed - pretending there aren't any
reading manifest file 'heudiconv.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'heudiconv.egg-info/SOURCES.txt'
running check
warning: Check: missing required meta-data: url

warning: Check: missing meta-data: if 'author' supplied, 'author_email' should be supplied too

creating heudiconv-0.0.0
creating heudiconv-0.0.0/heudiconv
creating heudiconv-0.0.0/heudiconv.egg-info
creating heudiconv-0.0.0/heudiconv/cli
creating heudiconv-0.0.0/heudiconv/external
creating heudiconv-0.0.0/heudiconv/external/tests
creating heudiconv-0.0.0/heudiconv/heuristics
creating heudiconv-0.0.0/heudiconv/tests
creating heudiconv-0.0.0/heudiconv/tests/data
creating heudiconv-0.0.0/heudiconv/tests/data/01-anat-scout
creating heudiconv-0.0.0/heudiconv/tests/data/01-fmap_acq-3mm
creating heudiconv-0.0.0/heudiconv/tests/data/b0dwiForFmap
copying files to heudiconv-0.0.0...
copying LICENSE -> heudiconv-0.0.0
copying README.rst -> heudiconv-0.0.0
copying pyproject.toml -> heudiconv-0.0.0
copying setup.cfg -> heudiconv-0.0.0
copying setup.py -> heudiconv-0.0.0
copying heudiconv/__init__.py -> heudiconv-0.0.0/heudiconv
copying heudiconv/bids.py -> heudiconv-0.0.0/heudiconv
copying heudiconv/convert.py -> heudiconv-0.0.0/heudiconv
copying heudiconv/dicoms.py -> heudiconv-0.0.0/heudiconv
copying heudiconv/due.py -> heudiconv-0.0.0/heudiconv
copying heudiconv/info.py -> heudiconv-0.0.0/heudiconv
copying heudiconv/main.py -> heudiconv-0.0.0/heudiconv
copying heudiconv/parser.py -> heudiconv-0.0.0/heudiconv
copying heudiconv/queue.py -> heudiconv-0.0.0/heudiconv
copying heudiconv/utils.py -> heudiconv-0.0.0/heudiconv
copying heudiconv.egg-info/PKG-INFO -> heudiconv-0.0.0/heudiconv.egg-info
copying heudiconv.egg-info/SOURCES.txt -> heudiconv-0.0.0/heudiconv.egg-info
...
copying heudiconv/tests/data/b0dwiForFmap/b0dwi_for_fmap+00001.dcm -> heudiconv-0.0.0/heudiconv/tests/data/b0dwiForFmap
copying heudiconv/tests/data/b0dwiForFmap/b0dwi_for_fmap+00002.dcm -> heudiconv-0.0.0/heudiconv/tests/data/b0dwiForFmap
copying heudiconv/tests/data/b0dwiForFmap/b0dwi_for_fmap+00003.dcm -> heudiconv-0.0.0/heudiconv/tests/data/b0dwiForFmap
Writing heudiconv-0.0.0/setup.cfg
creating dist
Creating tar archive
removing 'heudiconv-0.0.0' (and everything under it)

$> cat heudiconv.egg-info/PKG-INFO 
Metadata-Version: 2.1
Name: heudiconv
Version: 0.0.0
...
```
</details>

something like that is happening during building debian package distribution of heudiconv -- we get a new `heudiconv.egg-info/PKG-INFO` with new 0.0.0 version .

Do you see @jwodder some most legit way to preserve .egg-info/PKG-INFO if it  already exists?  shouldn't it be versioningit taking care about picking up known version from that file during that egg_info step somehow or producing some other persistent file in source distribution which would be picked up by python machinery somehow..?

just trying to figure out how to update debian packaging now

**Comment by yarikoptic** [comment]
more specifically in debian package building "egg overload" is happening during `/usr/bin/python3.9 setup.py install --root /build/heudiconv-0.11.1/debian/heudiconv` invocation so that is when I would need to avoid .egg-info/PKG-INFO being regenerated.

**Comment by jwodder** [comment]
> The "tricky" issue I encountered is that from that .tar.gz, if "derived" distribution (e.g. via `python setup.py sdist`) is attempted, it overwrites `heudiconv.egg-info/PKG-INFO` with new information containing dummy 0.0.0 version!

Did you have `versioningit` installed when you ran `python setup.py sdist`?  `versioningit` is primarily meant for use in a PEP 517 world, in which sdists are built using a frontend like `build`, which installs the build dependencies listed in the `pyproject.toml` (which include `versioningit`) before invoking setuptools.

**Comment by yarikoptic** [comment]
- versioningit was installed (I guess) in the `auto`mation workflow you made for heudiconv in https://github.com/nipy/heudiconv/pull/558 so .tar.gz was produced ok
- I indeed did not have it installed (there is no debian pkg yet to depend/install) within the debian package build environment. Installing it lead to #29 discovery
- apparently there is in recent versions of dh-python a pybuild-plugin-pyproject extra debian package which allows for PEP 517 world building
- with pip installed versioningit, and using that plugin which uses `-m build`, a symlinked PKG-INFO due to #29, I still get .egg-info overwritten with incorrect version

<details>
<summary>gory details </summary> 

```shell
root@smaug:/build/heudiconv-0.11.1# python3 -c 'import versioningit as m; print(m)'
<module 'versioningit' from '/usr/local/lib/python3.10/dist-packages/versioningit/__init__.py'>

root@smaug:/build/heudiconv-0.11.1# grep Vers heudiconv.egg-info/PKG-INFO  PKG-INFO
heudiconv.egg-info/PKG-INFO:Metadata-Version: 2.1
heudiconv.egg-info/PKG-INFO:Version: 0.11.1
PKG-INFO:Metadata-Version: 2.1
PKG-INFO:Version: 0.11.1

root@smaug:/build/heudiconv-0.11.1# ls -ld pyproject.toml 
-rw-r--r-- 1 pbuilder pbuilder 166 May 10 18:22 pyproject.toml

root@smaug:/build/heudiconv-0.11.1# python3.9 -m build --skip-dependency-check --no-isolation --wheel --outdir /build/heudiconv-0.11.1/.pybuild/cpython3_3.9_heudiconv 2>&1 | grep egg
running install_egg_info
running egg_info
writing heudiconv.egg-info/PKG-INFO
writing dependency_links to heudiconv.egg-info/dependency_links.txt
writing entry points to heudiconv.egg-info/entry_points.txt
writing requirements to heudiconv.egg-info/requires.txt
writing top-level names to heudiconv.egg-info/top_level.txt
reading manifest file 'heudiconv.egg-info/SOURCES.txt'
writing manifest file 'heudiconv.egg-info/SOURCES.txt'
Copying heudiconv.egg-info to build/bdist.linux-x86_64/wheel/heudiconv-0.0.0.egg-info
root@smaug:/build/heudiconv-0.11.1# grep Vers heudiconv.egg-info/PKG-INFO  PKG-INFO
heudiconv.egg-info/PKG-INFO:Metadata-Version: 2.1
heudiconv.egg-info/PKG-INFO:Version: 0.0.0
PKG-INFO:Metadata-Version: 2.1
PKG-INFO:Version: 0.0.0

```
</details>

**Comment by yarikoptic** [comment]
good catch on that!  I forgot that with `pip` I get it installed only for that version of python (in debian python3-* packages install for all python3 versions by default).  I have installed it now also for 3.9 .    After doing that it seems that the build is good now so heudiconv, given that we package versioningit for debian (according to https://ftp-master.debian.org/new.html might take months to get into Debian), could be adjusted to use versioningit at package build time using pybuild-plugin-pyproject  plugin.  With that I think this issue could be closed. Just FTR pasting here the head of the debian/rules for heudiconv where I had to make changes to get it working


```
#!/usr/bin/make -f

export DH_VERBOSE = 1
export PYBUILD_NAME = heudiconv
export PYBUILD_SYSTEM = pyproject

# for paranoid
export  http_proxy=http://127.0.0.1:9/

# to please datalad and git
export EMAIL=debian@example.com
export GIT_AUTHOR_NAME="The Name"
export GIT_COMMITTER_NAME=$(GIT_AUTHOR_NAME)
# export PYBUILD_BEFORE_TEST := cp -a heudiconv/tests {build_dir}/heudiconv/
export PYBUILD_BEFORE_TEST := cp -a heudiconv/tests {build_dir}/heudiconv/ && cp -a *.egg-info {build_dir}/
```
