### ISSUE TITLE
Default version if no tags

### ISSUE THREAD

**Issue by tlocke** [jwodder/versioningit#31]
Hi, thanks for your work on versioningit. Would it be possible to have a default version, say 0.0.0 if there are no tags found in the repository? The reason is that for testing, a shallow copy is often taken which doesn't have a tag, and so the install fails.

**Comment by jwodder** [comment]
`versioningit` already has this as a feature, [as mentioned in the docs](https://versioningit.readthedocs.io/en/stable/configuration.html#git).  Assuming you're using git, setting `default-tag` like so:

```toml
[tool.versioningit.vcs]
method = "git"
default-tag = "0.0.0"
```

will cause `versioningit` to act as though the initial commit is tagged with "`0.0.0`" if there are no tags in the repository.

**Comment by tlocke** [comment]
Thanks, sorry, I missed that.
