### ISSUE TITLE
Allow writing cmdclasses in `setup.cfg`

### ISSUE THREAD

**Issue by mttbernardini** [jwodder/versioningit#43]
Hi,

I noticed that in order to use the `onbuild` step, I need to explicitly create a `setup.py` and invoke `setup()` by passing the `cmclasses` returned by `versioningit.get_cmdclasses()`.

Since `setuptools` supports the definition of cmdclasses in `setup.cfg` (and potentially `pyproject.toml`, I didn't check, see https://github.com/pypa/setuptools/issues/2570 for reference), would it be possible to expose the needed cmdclasses in the `cmdclasses.py` module so that they can be used in this form, avoiding having to create a `setup.py` specifically for this use case?

Thank you for this tool, it's quite helpful!

**Comment by jwodder** [comment]
Thanks for the suggestion!  My apologies for the delay.  I've implemented this in PR #44; unless I hear otherwise, I plan to merge & release in one week.

**Comment by jwodder** [comment]
This feature is now available in versioningit v2.2.0.
