### ISSUE TITLE
can you calculate the 'next_version' ?

### ISSUE THREAD

**Issue by vurt007** [jwodder/versioningit#6]
love the project, but feel like I might be missing something ..
I'd like to be able to print or write the 'next_version'  ( or the next release version ) 
e.g.
current tag = 0.2.0
distance version on branch (format "{version}.post{distance}") =  0.2.0.post7
next_version (smallest-release) =  0.2.1

how do I print (or write) the 'next version'   ..  for example if I wanted to  tag a repo after merge into the main branch
e.g `git tag $(versioningit -n)`

I'm happy to open a PR to support this, but wanted to check, am I missing something about how this package should be used ?

**Comment by jwodder** [comment]
While currently (as of v0.2.1), the command-line interface does not support getting the next version, it is possible to compute it using `versioningit`'s Python API.  While the relevant part of the API is documented in the sense of "has docstrings", it's not mentioned in the README, as I think we can both agree the README is long enough as-is.  (If/when this project gets a Readthedocs site, it would be documented there, though.)

However, in response to your post, I've added a `get_next_version()` function (not listed in the README, though the README now at least points out that there are aspects of the API not listed there) and an `-n`/`--next-version` CLI flag for getting the next version of a project.  These features are currently available on the project's master branch, and, if you are satisfied with them, I will release v0.3.0 with them soon.

**Comment by vurt007** [comment]
that's great, thanks for the quick turnaround

**Comment by jwodder** [comment]
Versioningit v0.3.0 has now been released.
