### ISSUE TITLE
Best way of getting the version from vcs in editable install falling back to metadata for regular install

### ISSUE THREAD

**Issue by jenshnielsen** [jwodder/versioningit#8]
I would like to achieve something similar to how versioneer works such that I get the version number from git describe if I am in an editable install using imporlib_metadata.version if not

Currently I ended up doing something like this:
```python
from importlib.metadata import version
from importlib.resources import files

def get_package_version(package_name: str) -> str:
    maybe_package_root = files(package_name).parent
    if maybe_package_root / "pyproject.toml").exists():
        import versioningit
        __version__ = versioningit.get_version(project_dir=maybe_package_root)
    else:
        __version__ = version(package_name)
    return __version__
```

So my questions are 
1) Is there a better way of doing this that I have overlooked. https://github.com/jwodder/versioningit/issues/3 could be one 
way of solving this since I could put the editable install flow into a file and let the custom cmd_class overwrite it when generating a package. 
2) If not is there any interest in putting a cleaner version of this into versioningit (would need to handle different source layouts at least)

**Comment by jwodder** [comment]
(Disclaimer: I rarely ever use editable installs.)

I'm not clear on what problem you're trying to solve here.  If I test out `python setup.py develop`/`pip install -e .` on a versioningit-enabled project that does `__version__ = importlib.metadata.version("project-name")`, I can retrieve the project's version from its `__version__`, though it becomes out of date once a commit is made unless the project is re-installed.  Is the problem the need to keep re-installing?  That would still be an issue with #3.

**Comment by jenshnielsen** [comment]
Yes keeping to reinstall is a deal breaker for the particular workflow that I have in mind since an editable install may change to point to a different branch have new commits etc without a reinstall (at least for pure python projects which is all I am concerned with here) 

IMHO it would have been great if pep 660 defined a more consistent way of keeping the metadata of an editable install up to date but it unfortunatly does not so metadata of an editable pacage for now is just the version that was installed.

My idea with #3 was that one could potentially have a file that contained something like:

__version__ = versioningit.get_version(project_dir=package_root)

and let that be over written by 

__version__ == thetagedversio

or

__version__ = importlib.metadata.version("projectname") 

When a package is generated. That is largely how versionner works (the _version.py file contains significantly more code but thats just an artefact of the way they vendor code rather than making it a library)

**Comment by jwodder** [comment]
@jenshnielsen Your interest in #3 has motivated me to finally get around to implementing it.  See #18 for the PR (and commit 1398b18 for the documentation) and let me know if that meets your needs.

**Comment by jenshnielsen** [comment]
Thanks I will have a look as soon as possible

**Comment by jwodder** [comment]
OK, I'm taking no news as good news and merging.

**Comment by provtemp** [comment]
I am interested in the same functionality (install in editable mode, make changes to the installed code, get the fresh version without re-installing). I do not see how generating a file at build/setup/install time would help (consider a workflow where you install something in editable mode once and then never again, using only `git pull` to upgrade, then importlib would report `0.0.1` while, due to years of `git pull`, you actually have the latest version `23.42.69`).

I tinkered with `versioningit.get_version(config={},project_dir=os.path.basename(__file__))` (in Python `>= 3.7` where `__file__` should be absolute), which seems to work, except when the package is installed in a different repository (that might happen with `git clone x; cd x; python -m venv venv; venv/bin/activate; pip install y`, then y would probably get the version of x instead of y, so something more is needed to handle that case).

**Comment by jenshnielsen** [comment]
@jwodder Sorry I have been fully ocupied with other stuff I will give this a test now.

@provtemp The idea is that you have something like 

```
__version__ = versioningit.get_version(config={},project_dir=os.path.basename(__file__))
```
In a file in your package and then upon generation of an sdist or a bdist that file gets overwritten with

```
__version__ = "x.y.z"
```
where x.y.z is the version that you are generating an sdist/bdist for

**Comment by jenshnielsen** [comment]
@jwodder Finally had a chance to test this out and it works great. As far as I am concerned this issue can be closed
