### ISSUE TITLE
Command versioningit is not normalizing version  

### ISSUE THREAD

**Issue by eferreira4** [jwodder/versioningit#87]
I have have the following  settings in `pyproject.toml` ie the versioneer format

```
[tool.versioningit.format]
distance = "{base_version}+{distance}.{vcs}{rev}"
# Example formatted version: 1.2.3+42.ge174a1f

dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"
# Example formatted version: 1.2.3+42.ge174a1f.dirty

distance-dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"
# Example formatted version: 1.2.3+42.ge174a1f.dirty
```
And running the lastest release `3.1.1`
```sh
versioningit -V
versioningit 3.1.1
```

I created the following tags in my repo `v0.1.0-rc0`.
When i run `versioningit` i get the following output:
```sh
versioningit 
0.1.0-rc0
```

While if do the local install package ie `pip install -e .` and list the installed packages i see the correct normalized version according to PEP440 (ie `-` is removed when `rc` is present)
```sh
pip list
...
my_package 0.1.0rc0  /data/packages/software/my_package
...
```

I would expect the command line tool `versioningit`  to also show me the same normalized (according to PEP440) output.

I also tried for other tags `v0.1.0-a1`, `v0.1.0-post1` and `v0.1.0_b2` , with the similar behavior, ie `versiongit` not showing the normalized versions.

**Comment by jwodder** [comment]
`versioningit` does not normalize versions, nor do I intend to make it do so.  The normalization of the installed package version is due to setuptools, which further processes the version calculated by `versioningit` when preparing the package.

**Comment by eferreira4** [comment]
> `versioningit` does not normalize versions, nor do I intend to make it do so. The normalization of the installed package version is due to setuptools, which further processes the version calculated by `versioningit` when preparing the package.

I was just trying to understand what was the expected output.

I guess this part of the documentation made me assume that normalization was happening inside `versiongit` at least for the `version-tuple` generation.

```
pep440boolean
(optional) If true (default: false), the project version will be parsed & normalized as a [PEP 440](https://peps.python.org/pep-0440/) version (If is not valid, an error will occur), and {version_tuple} will consist of the following items, in order:
```
